# [START runtime]
runtime: nodejs10
env_variables:
  MONGO_DB: 'mongodb+srv://shogunross:truesoul1995@chatbotdatabase-y4vvz.gcp.mongodb.net/hospital-management?retryWrites=true'
  SECRET: 'somesupersecretkey'
# [END runtime]
