version: '3'
services:
  app:
    container_name: hospital-management-backend
    restart: always
    build: .
    ports:
      - '80:8000'
    links:
      - mongo
  mongo:
    container_name: mongo-container
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=hospital-management
      - MONGO_INITDB_ROOT_USERNAME=AdminLong
      - MONGO_INITDB_ROOT_PASSWORD=5101995
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./data:/data/db	
