FROM node:12

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

# ARG MONGO_DB
# ARG ACCESS_TOKEN_SECRET
# ARG REFRESH_TOKEN_SECRET
# ARG CONFIRM_TOKEN_SECRET
# ARG PASSWORD_TOKEN_SECRET
# ARG FRONTEND_URL
# ARG BACKEND_URL
# ARG GMAIL_USER
# ARG GMAIL_PASSWORD

ENV MONGO_DB=mongodb+srv://shogunross:truesoul1995@chatbotdatabase-y4vvz.gcp.mongodb.net/hospital-test?retryWrites=true
ENV ACCESS_TOKEN_SECRET=SUPERSECRETAPP
ENV REFRESH_TOKEN_SECRET=SUPERSECRETREFRESHTOKEN
ENV CONFIRM_TOKEN_SECRET=SUPERSECRETAPP
ENV PASSWORD_TOKEN_SECRET=SUPERSECRETAPP
ENV FRONTEND_URL=https://hospital-management-web-2022.herokuapp.com
ENV BACKEND_URL=https://hospital-management-2022.herokuapp.com
ENV GMAIL_USER=hydroponicshubproject@gmail.com
ENV GMAIL_PASSWORD=Truesoul1995$

EXPOSE 8000

CMD ["npm", "start"]