version: '3'
services:
  app:
    container_name: hospital-management-backend
    restart: always
    build: .
    ports:
      - '80:8000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
